apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: configserver-testing-git-auth

spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        carto.run/workload-name: configserver-testing

  service:
    apiVersion: v1
    kind: Secret
    name: configserver-git-auth

--- 
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: configserver-testing-encrypt-key

spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        carto.run/workload-name: configserver-testing

  service:
    apiVersion: v1
    kind: Secret
    name: configserver-encrypt-key